In [1]:
import pandas as pd

In [2]:
dt = pd.read_csv('Pokemon.csv')
dt

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [4]:
dt["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [7]:
dt.sort_values("Speed", ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
431,386,DeoxysSpeed Forme,Psychic,NaN,600,50,95,90,95,90,180,3,True
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,597,Ferroseed,Grass,Steel,305,44,50,91,24,86,10,5,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
359,328,Trapinch,Ground,NaN,290,45,100,45,45,45,10,3,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
495,446,Munchlax,Normal,NaN,390,135,85,40,40,85,5,4,False

In [11]:
attack_mean = dt["Attack"].mean()
def set_attack(val):
    if val < attack_mean:
        return "Attack_low"
    else:
        return "Attack_high"
    
dt["Attack_High_Low"] = dt["Attack"].apply(set_attack)
dt

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_High_Low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack_low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack_low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack_high
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack_high
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack_low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack_high
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack_high
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack_high
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack_high
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack_high

In [13]:
speed_mean = dt["Speed"].mean()
def set_speed(value):
    if value < speed_mean:
        return "Speed id low"
    else:
        return "Speed is high"
dt["High_Low_Speed"] = dt["Speed"].apply(set_speed)
dt

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_High_Low,High_Low_Speed
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack_low,Speed id low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack_low,Speed id low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack_high,Speed is high
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack_high,Speed is high
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack_low,Speed id low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack_high,Speed id low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack_high,Speed is high
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack_high,Speed is high
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack_high,Speed is high
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack_high,Speed is high

In [15]:
HP_mean = dt["HP"].mean()
def set_HP(x):
    if x < HP_mean:
        return "HP is low"
    else:
        return "HP is high"
dt["High_Low_HP"] = dt["HP"].apply(set_HP)
dt

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_High_Low,High_Low_Speed,High_Low_HP
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack_low,Speed id low,HP is low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack_low,Speed id low,HP is low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack_high,Speed is high,HP is high
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack_high,Speed is high,HP is high
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack_low,Speed id low,HP is low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack_high,Speed id low,HP is low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack_high,Speed is high,HP is low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack_high,Speed is high,HP is high
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack_high,Speed is high,HP is high
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack_high,Speed is high,HP is high